version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: 0107
      POSTGRES_DB: live_trade_db
    ports:
      - "5434:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    # volumes:
    #   - ./grafana-data:/var/lib/grafana
    depends_on:
      - postgres

  live_trade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_trade_app
    restart: always
    working_dir: /live_trade